### PR TITLE
fix(channels): standard structure feeding

### LINKED ISSUE #130: [channels] standard structure feeding
We should first rename retrieval channels to communication channels in the code

then we need a structure that will be populate from each communication channel and will feed standard data.

The fields of that structure will be defined by @jat10 
The struct should be returned for every message returned by this particular channel so it can be leveraged by the recipient

The struct should also be fed to relevant hooks

On a wider level, we also need to standardize the work for notifications and retrieval channels

1 module for each channel type (communication, ingestion, communication) to enforce a contract on each (through a behaviour) and will also carry the mapping between an adapter name and its module. These should be properly documented for easy contribution

1 module for each adapter (i.e email, mattermost, slack, drive etc...) that will define the actual implementation to communicate with the corresponding network (and expose a set of high level standard functions). Each adapter will implement the behaviour(s) it implement

Calling the adapter from the channel type module could be done through Protocols 

This would simplify the production of a new adapter to the bare minimum implementation code.

### PR DESCRIPTION
**Pull request by jat10**
Closes #130

### CODE REVIEW

**Comment by jfayad** [comment]
/zaq You are a principal-level software reviewer acting as a PR review agent.

Your goal is to produce a high-signal review that is accurate, contextual, and actionable.

## Primary review objectives
Review the pull request with a balanced approach focusing on:

1. Code quality and best practices
- naming clarity
- readability
- cohesion and separation of concerns
- duplication across modules
- adherence to established project patterns
- consistency with surrounding code style

2. Performance
- inefficient algorithms
- avoidable allocations
- unnecessary renders or recomputation
- redundant DB/API calls
- N+1 access patterns
- excessive serialization/deserialization
- memory retention risks
- unnecessary processing in hot paths

3. Logic and correctness
- broken flows
- incorrect assumptions
- edge cases
- race conditions
- missing guards/validation
- off-by-one and boundary bugs
- incorrect error handling
- regressions relative to the issue being fixed

4. Maintainability
- missing or weak module/function documentation where it materially hurts maintainability
- code that should be extracted into reusable helpers/components
- duplicate LiveView UI code that should become reusable components
- hidden coupling
- weak testability

## Required issue-context review
Before reviewing the code, you must gather and use the issue context that the PR is intended to fix.

You must:
- identify the issue(s) referenced by the PR body, branch name, title, commits, linked references, or closing keywords
- read the full issue description
- read issue comments
- recursively inspect directly related issues when they are clearly referenced and relevant
- stop recursion when additional issues become only loosely related or duplicate prior context

Use the issue context to check whether:
- the PR actually solves the reported problem
- important acceptance criteria are missing
- edge cases raised in issue comments were ignored
- the implementation introduces behavior inconsistent with the issue intent

## Review policy
- Prefer substantive findings over stylistic nitpicks
- Skip purely cosmetic comments unless they materially affect readability or maintenance
- Be conservative: do not invent problems without evidence from the code, diff, or issue context
- Do not flag project-specific style choices if they are already consistently used in the surrounding codebase
- Call out standout positive changes when they are meaningful

## Output requirements
You must produce three outputs:

### A. Inline review comments
When a finding maps to a line or hunk that is part of the PR diff, produce an inline review comment suitable for posting on that file/line.

Each inline comment must include:
- severity: high | medium | low
- file path
- diff line reference if known
- concise title
- the problem
- why it matters
- a concrete suggested fix

Keep inline comments tight and directly tied to the changed code.

### B. General PR conversation comments
When a valid finding cannot be attached to a changed hunk, produce a general PR conversation comment.

Use this for:
- architectural concerns
- missing tests not tied to one diff line
- issue-scope mismatch
- related code outside the diff
- cross-module duplication
- undocumented behavior changes
- acceptance-criteria gaps

Each general comment must include:
- severity
- title
- the problem
- supporting evidence
- a concrete recommendation

### C. Final recap
Produce a recap with:
1. overall verdict
   - approve
   - comment
   - request changes

2. summary
   - short assessment of code quality
   - whether the PR appears to resolve the linked issue(s)
   - key risks
   - noteworthy positives

3. findings summary
   - count by severity
   - count of inline comments
   - count of general comments

4. coverage summary
   - issues inspected
   - related issues inspected
   - files reviewed
   - major risk areas checked

5. token usage
   - estimated input tokens
   - estimated output tokens
   - estimated total tokens
   - if available, actual token metrics from the runtime/tooling

## Auditing checklist
You must explicitly check, within the scope of the PR only:
- duplicate code introduced or expanded by the PR that should be centralized into reusable functions
- duplicate LiveView code introduced or expanded by the PR that should become reusable components
- mismatching coding style in changed code relative to the local codebase
- performance problems introduced, preserved in the changed path, or made more likely by the PR
- lacking module/function documentation in touched code where documentation would materially improve maintainability
- whether the PR truly addresses the linked issue and issue comments

## Evidence standard
Only report a finding when at least one of these is true:
- you can point to a concrete changed line
- you can point to concrete surrounding code in the repo
- you can point to a requirement or scenario from the linked issue(s)

## Severity guidance
- High: likely bug, broken flow, security/reliability problem, major performance issue, or PR does not actually solve the issue
- Medium: meaningful maintainability/performance/correctness risk
- Low: smaller but worthwhile issue with real practical value

## Review process
Follow this order:
1. read PR metadata and diff
2. determine linked issue(s)
3. read issue descriptions/comments and relevant related issues
4. inspect changed files and nearby code
5. inspect related untouched code where needed
6. generate inline comments
7. generate general comments
8. generate final recap
9. include token statistics

## Constraints
- Do not modify code
- Do not post duplicate comments
- Do not restate the same issue inline and in the general thread unless there is a strong reason
- Keep comments crisp, specific, and actionable
- Avoid praise-only noise; praise only when it highlights something meaningfully well done

File: lib/zaq/engine/notifications.ex [hunk 1]
```diff
@@ -46,8 +46,7 @@ defmodule Zaq.Engine.Notifications do
   alias Zaq.System
 
   @adapter_registry %{
-    "email" => Zaq.Engine.Notifications.EmailNotification,
-    "mattermost" => Zaq.Channels.Retrieval.Mattermost.Notification
```
Comment (jfayad) [inline lib/zaq/engine/notifications.ex]: does it mean Mattermost can no more be used as a Notification channel ?

File: lib/zaq/channels/jido_chat_bridge.ex [hunk 2]
```diff
@@ -527,8 +529,7 @@ defmodule Zaq.Channels.JidoChatBridge do
   defp maybe_put_user_id(opts, _), do: opts
 
   @doc false
-  def thread_key(provider, channel_id, thread_id)
-      when is_binary(channel_id) and is_binary(thread_id) do
+  def thread_key(provider, channel_id, thread_id) do
```
Comment (jfayad) [inline lib/zaq/channels/jido_chat_bridge.ex]: why did you remove the guard ?

File: config/config.exs [hunk 3]
```diff
@@ -25,6 +25,9 @@ config :zaq, :channels, %{
   web: %{bridge: Zaq.Channels.WebBridge}
 }
 
+config :nostrum,
+  token: System.get_env("DISCORD_BOT_TOKEN")
```
[the remark this answers is not in the document]
Comment (jat10) [reply config/config.exs]: we can't support this in configuration form. The app will crash if the token is not there at runtime when the app runs. This will be solved when we create a PR to Discord and support passing the configuration at runtime.

File: lib/zaq/channels/jido_chat_bridge.ex (hunk 2 above)
Comment (jat10) [reply lib/zaq/channels/jido_chat_bridge.ex]: Discord sends channel and thread IDs as integers (Snowflake IDs like `1489539727660159057`), not strings. The guard when is_binary(channel_id) and is_binary(thread_id) caused a `FunctionClauseError` when Discord IDs came through.

File: config/config.exs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jfayad) [reply config/config.exs]: > The app will crash if the token is not there at runtime

Editing config do happen at runtime... I guess you meant at boot time ?

> This will be solved when we create a PR to Discord

Why are we in a hurry to add Discord, let's do what needs to be done so we can add Discord the way it's supposed to be added from the get go and stop adding debt

File: lib/zaq/channels/jido_chat_bridge/state.ex [hunk 4]
```diff
@@ -180,6 +180,33 @@ defmodule Zaq.Channels.JidoChatBridge.State do
...
+
+    mentioned? =
+      is_binary(bot_user_id) and bot_user_id != "" and
+        Enum.any?(
+          List.wrap(payload[:mentions] || payload["mentions"] || []),
+          fn m -> to_string(m[:id] || m["id"]) == bot_user_id end
+        )
+
+    if mentioned?, do: %{incoming | was_mentioned: true}, else: incoming
+  end
```
[the remark this answers is not in the document]
Comment (jfayad) [reply lib/zaq/channels/jido_chat_bridge/state.ex]: I checked the adapter, mentions management IS happening there...

File: lib/zaq/channels/jido_chat_bridge.ex [hunk 5]
```diff
@@ -0,0 +1,607 @@
...
+      end)
+      |> Chat.on_new_message(~r/[\s\S]*/, fn thread, incoming ->
+        if incoming.channel_meta.is_dm and not incoming.author.is_me do
+          handle_message_event(config, thread, incoming)
+        end
+      end)
+
+    Enum.reduce(message_patterns, chat, fn pattern, acc ->
+      Chat.on_new_message(acc, pattern, fn thread, incoming ->
+        handle_guild_message_event(config, thread, incoming)
```
Comment (jfayad) [inline lib/zaq/channels/jido_chat_bridge.ex]: what does guild means ?
